// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messageId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MessageId {

  /// <summary>Holder for reflection information generated from messageId.proto</summary>
  public static partial class MessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for messageId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9tZXNzYWdlSWQucHJvdG8SCU1lc3NhZ2VJZCorCgdNZXNzYWdlEggKBE5v",
            "bmUQABIJCgVNdWx0aRABEgsKBlNpZ25JbhDQD2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MessageId.Message), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Message {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("Multi")] Multi = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SignIn")] SignIn = 2000,
  }

  #endregion

}

#endregion Designer generated code
